# Generated by Django 5.0.6 on 2024-07-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='isbn',
        ),
    ]
