# Generated by Django 5.0.6 on 2024-07-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100, unique=True)),
                ('additional_info', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(default=50)),
                ('book_count', models.PositiveSmallIntegerField(default=0)),
                ('books', models.ManyToManyField(blank=True, help_text='books that are currently rented', to='books.book')),
            ],
        ),
    ]
